services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - compiler

  compiler:
    build: ./Compiler
    ports:
      - "5001:5001"
    volumes:
      - ./Compiler:/app
    environment:
      - NODE_ENV=production 