services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production
      - COMPILER_URL=http://compiler:8000/compile
    depends_on:
      - compiler

  compiler:
    build: ./Compiler
    ports:
      - "8000:8000"
    volumes:
      - ./Compiler:/app
    environment:
      - NODE_ENV=production 